name: DotnetBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    #- name: Super-Linter
    #  uses: github/super-linter@v4.9.4
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    #- name: Install Sonar global tool
    #  run: dotnet tool install --global dotnet-sonarscanner
    - name: Begin Sonar scan
      run: dotnet sonarscanner begin /k:"AkkiTestGithub" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=${{ secrets.SONAR_HOST_URL }}
      
    - name: Build and run unit tests
      run: |
        dotnet restore 
        dotnet build --no-restore
    - name: End Sonar scan
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }} 
    #- name: Official SonarQube Scan
    #  uses: SonarSource/sonarqube-scan-action@v1.1.0
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name:  Publish
      run: dotnet publish 
    - name:  Run Dotnet app
      run: RUNNER_TRACKING_ID="" && (nohup dotnet ${{ github.workspace }}/bin/Debug/net6.0/MyWebApp.dll &  )
    
